apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-swagger-ui
  labels:
    app: swagger-ui
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:v3.31.1
          ports:
            - name: swagger-ui-port
              containerPort: 8080
