apiVersion: v1
kind: Pod
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  containers:
    - name: swagger-ui
      image: swaggerapi/swagger-ui:v3.31.1
      ports:
        - name: swagger-port
          containerPort: 8080
