apiVersion: v1
kind: Service
metadata:
  name: swaggerui-service
spec:
  ports:
    - port: 8080
      targetPort: swagger-ui-port
      protocol: TCP
  selector:
    app: swagger-ui
  type: LoadBalancer
