apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerui-deployment
  labels:
    app: swagger-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:v3.31.1
          ports:
            - name: swagger-ui-port
              containerPort: 8080
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swaggerui-secrets
                  key: password
            - name: TESTING_HOST
              value: 127.0.0.1
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 35
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 35
        - name: nginx-swagger-ui
          image: nginx:latest
          ports:
            - name: nginx-port
              containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-volume
          configMap:
            name: nginx-config
            items:
              - key: nginx-reverseproxy.conf
                path: nginx-reverseproxy.conf
